[build]
command = "npm run build"
functions = "netlify/functions" # Compiled output directory for functions
publish = "out" # Output directory for Next.js static files

[functions]
directory = "netlify/functions"
