[build]
command = "npm run build"
publish = ".next" # The directory for Next.js output

[functions]
directory = "netlify/functions"
node_bundler = "zisi"

# Enable Netlify Identity
[build.environment]
  NODE_VERSION = "18"
  NETLIFY_IDENTITY = "enabled"

# Netlify Identity configuration is handled automatically

# Enable Identity service
[template.environment]
  NETLIFY_AUTH_PROVIDERS = "email,google,github"

# Additional headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"